name: Run Scraper

on:
  schedule:
    - cron: '30 11 * * 1-5'   # 07:30 ET
    - cron: '30 13 * * 1-5'   # 09:30 ET
    - cron: '0 17 * * 1-5'    # 12:00 ET
    - cron: '30 20 * * 1-5'   # 15:30 ET
    - cron: '0 23 * * 1-5'    # 18:00 ET

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
        run: python main.py
